pipeline:
#  setup:
#    image: docker
#    commands:
#      # - docker build --rm -t foo/bar:baz .
#      # http://paislee.io/how-to-build-and-deploy-docker-images-with-drone/
#      # https://github.com/drone/drone/issues/1609#issuecomment-304986851
#      - docker build --rm -t kgantsov/stockholm_commute_bot_app:latest --no-cache .
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
  build:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: kgantsov/stockholm_commute_bot_app
    tag: latest
    file: Dockerfile

pipeline:
  slack:
    image: plugins/slack
    channel: dev
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]